#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 openwrt-system-monitor
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
START=99
STOP=15
NAME=sysmonitor
APP_PATH=/usr/share/$NAME

stop()
{
	set sysmonitor.sysmonitor.enable=0
	set commit sysmonitor
}
start()
{
	/etc/init.d/ttyd restart
	sed -i "/coremark.sh/d" /etc/crontabs/root

	if [ $(uci get sysmonitor.sysmonitor.bbr) == 1 ];  then
		sysctl -w net.ipv4.tcp_congestion_control=bbr
	else
		sysctl -w net.ipv4.tcp_congestion_control=cubic
	fi
	if [ -f "/etc/init.d/smartdns" ]; then
		if [ $(uci get sysmonitor.sysmonitor.smartdnsAD) == 1 ];  then
			sed -i s/'#conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf'/'conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf'/ /etc/smartdns/custom.conf
		else
			sed -i s/'#conf-file'/'conf-file'/ /etc/smartdns/custom.conf
			sed -i s/'conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf'/'#conf-file \/etc\/smartdns\/anti-ad-for-smartdns.conf'/ /etc/smartdns/custom.conf	
		fi
		/etc/init.d/smartdns restart &
	fi
	$APP_PATH/sysapp.sh getip
	$APP_PATH/sysapp.sh getip6
	set sysmonitor.sysmonitor.enable=1
	set commit sysmonitor
	$APP_PATH/sysmonitor.sh &
}

