#!/bin/sh /etc/rc.common
#
# Copyright (C) 2017 openwrt-system-monitor
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
START=99
STOP=15
NAME=sysmonitor
APP_PATH=/usr/share/$NAME

stop()
{
	uci set sysmonitor.sysmonitor.enable=0
	uci commit sysmonitor
}
start()
{
	uci set sysmonitor.sysmonitor.enable=1
	uci commit sysmonitor
	sed -i "/coremark.sh/d" /etc/crontabs/root
	$APP_PATH/sysapp.sh vpn
	$APP_PATH/sysapp.sh getip
	$APP_PATH/sysapp.sh setdns
	$APP_PATH/sysapp.sh set_smartdns
	$APP_PATH/sysmonitor.sh &
}
