#!/bin/sh

uci set fstab.@global[0].anon_mount='1'
uci commit fstab

uci set system.@system[0].hostname='VAIOBYN'
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci commit system

uci set wireless.radio0.channel='auto'
uci set wireless.default_radio0.ssid='VAION'
uci set wireless.default_radio0.key='sonyvaiotz13w'
uci set wireless.radio0.disabled='1'
uci set wireless.default_radio0.disabled='1'
uci commit wireless
wifi up

uci set network.globals.ula_prefix=''
#uci set network.@device[0].mtu='1472'
#uci set network.@device[0].stp='1'
uci set network.lan.ipaddr='192.168.1.110'
uci set network.lan.netmask='255.255.255.0'
uci set network.lan.gateway='192.168.1.1'
uci del_list network.lan.dns='192.168.1.1'
uci add_list network.lan.dns='192.168.1.1'
uci set network.lan.ip6assign=''
uci commit network

cat /etc/config/network | grep lan6 > /dev/null
if [ $? -ne 0 ];then
cat >>/etc/config/network <<EOF
config interface 'lan6'
	option proto 'dhcpv6'
	option device 'br-lan'
	option reqaddress 'try'
	option reqprefix 'auto'
EOF
fi

uci del_list dhcp.lan.list ra_flags='none'
uci add_list dhcp.lan.list ra_flags='none'
uci set dhcp.lan.ra=''
uci set dhcp.lan.dhcpv4=''
uci set dhcp.lan.dhcpv6=''
uci set dhcp.lan.ignore='1'
uci set dhcp.@dnsmasq[0].localservice='0'
uci set dhcp.@dnsmasq[0].domainneeded='0'
uci commit dhcp

cat /etc/config/dhcp | grep lan6 > /dev/null
if [ $? -ne 0 ];then
cat >> /etc/config/dhcp <<EOF
config dhcp 'lan6'
	option interface 'lan6'
	option ignore '1'
	list ra_flags 'none'

config domain
	option name 'NAS'
	option ip '192.168.1.8'
EOF
fi

uci del_list firewall.@zone[0].network='lan6'
uci add_list firewall.@zone[0].network='lan6'
uci set firewall.@defaults[0].flow_offloading='1'
uci set firewall.@defaults[0].flow_offloading_hw='0'
uci set firewall.@defaults[0].input='ACCEPT'
uci set firewall.@defaults[0].output='ACCEPT'
uci set firewall.@defaults[0].forward='ACCEPT'

uci set firewall.@zone[0].input='ACCEPT'
uci set firewall.@zone[0].output='ACCEPT'
uci set firewall.@zone[0].forward='ACCEPT'
uci set firewall.@zone[0].masq='0'
uci set firewall.@zone[0].mtu_fix='0'
uci set firewall.@zone[1].input='ACCEPT'
uci set firewall.@zone[1].output='ACCEPT'
uci set firewall.@zone[1].forward='ACCEPT'
uci set firewall.@zone[1].masq='0'
uci set firewall.@zone[1].mtu_fix='0'

uci set firewall.@rule[0].src='lan'
uci set firewall.@rule[1].src='lan'
uci set firewall.@rule[2].src='lan'
uci set firewall.@rule[3].src='lan'
uci set firewall.@rule[4].src='lan'
uci set firewall.@rule[5].src='lan'
uci set firewall.@rule[6].src='lan'
uci set firewall.@rule[7].src='lan'
uci set firewall.@rule[8].src='lan'
uci set firewall.@rule[7].dest='*'
uci set firewall.@rule[8].dest='*'
uci commit firewall

cat /etc/config/network | grep wghome > /dev/null
if [ $? -ne 0 ];then
cat >> /etc/config/network <<EOF
config interface 'wghome'
	option proto 'wireguard'
	option private_key 'CEhlQo1JZz/QcFjjYDq14LgTXbsSgVlPq7bXa0IBHlg='
	list addresses '192.168.9.110/24'
	list addresses '192.168.8.110/24'
	list addresses '192.168.7.110/24'
	list addresses '192.168.6.110/24'
	option listen_port '58888'

config wireguard_wghome
	option public_key 'RuCdaOHKPDf2c2kihx2dzBhEDKZnbnhP1N4aUBkzw3A='
	option route_allowed_ips '1'
	list allowed_ips '192.168.8.0/24'
	option description 'Iphone8Plus'

config wireguard_wghome
	option public_key 'HkRSRzDMks74AmFQlnByouVNR6E/o5I+j033QqF1UyI='
	option route_allowed_ips '1'
	list allowed_ips '192.168.7.0/24'
	option description 'Iphone6'

config wireguard_wghome
	option public_key 'ql9g9ngGQMq9cyBaun5QjnyROyh7Cu4zJ9eZwFM6UGw='
	option route_allowed_ips '1'
	list allowed_ips '192.168.6.0/24'
	option description 'Iphone8'
EOF
fi
cat /etc/config/firewall | grep wghome > /dev/null
if [ $? -ne 0 ];then
cat >> /etc/config/firewall <<EOF
config zone
	option name 'wghome'
	option input 'ACCEPT'
	option output 'ACCEPT'
	option forward 'ACCEPT'
	list network 'wghome'

config forwarding
	option src 'wghome'
	option dest 'lan'

config rule
	option name 'Wireguard'
	option src 'lan'
	option src_port '58888'
	option dest_port '58888'
	option target 'ACCEPT'
EOF
fi

[ -f /etc/init.d/ddns ] && {
/etc/init.d/ddns enable
cat > /etc/config/ddns <<EOF
config ddns 'global'
	option ddns_dateformat '%F %R'
	option ddns_loglines '250'
	option ddns_rundir '/var/run/ddns'
	option ddns_logdir '/var/log/ddns'
	option upd_privateip '1'

config service 'ChangeipECS'
	option service_name 'changeip.com'
	option use_ipv6 '0'
	option enabled '1'
	option username 'sqmshcn@gmail.com'
	option password 'sqmshcn110'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option ip_source 'web'
	option ip_url 'http://47.100.183.141/ip.php'
	option lookup_host 'ecs.freeddns.com'
	option domain 'ecs.freeddns.com'
	option interface 'br-lan'
	option bind_network 'lan'
	option force_dnstcp '1'

config service 'DynuVAIO'
	option service_name 'dynu.com'
	option use_ipv6 '0'
	option lookup_host 'vaiocn.ddnsfree.com'
	option domain 'vaiocn.ddnsfree.com'
	option username 'sqmshcn'
	option password 'dynuddns'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option ip_source 'web'
	option ip_url 'http://members.3322.org/dyndns/getip'
	option enabled '1'
	option interface 'br-lan'
	option bind_network 'lan'
	option force_dnstcp '1'

config service 'DynuHOME'
	option service_name 'dynu.com'
	option use_ipv6 '0'
	option enabled '1'
	option ip_source 'web'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_url 'http://members.3322.org/dyndns/getip'
	option lookup_host 'homecn.ddnsfree.com'
	option domain 'homecn.ddnsfree.com'
	option bind_network 'lan'
	option interface 'br-lan'
	option force_dnstcp '1'

config service 'DynuNAS'
	option service_name 'dynu.com'
	option use_ipv6 '0'
	option enabled '1'
	option ip_source 'web'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_url 'http://members.3322.org/dyndns/getip'
	option lookup_host 'nascn.ddnsfree.com'
	option domain 'nascn.ddnsfree.com'
	option bind_network 'lan'
	option interface 'br-lan'
	option force_dnstcp '1'

config service 'DynuSSR'
	option service_name 'dynu.com'
	option use_ipv6 '0'
	option enabled '1'
	option ip_source 'web'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option username 'sqmshcn'
	option password 'dynuddns'
	option ip_url 'http://members.3322.org/dyndns/getip'
	option lookup_host 'ssrcn.ddnsfree.com'
	option domain 'ssrcn.ddnsfree.com'
	option bind_network 'lan'
	option interface 'br-lan'
	option force_dnstcp '1'

config service 'DynuVAIO6'
	option service_name 'dynu.com'
	option use_ipv6 '1'
	option enabled '1'
	option username 'sqmshcn'
	option password 'dynuddns'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option ip_source 'web'
	option ip_url 'http://192.168.1.120/ip6.html'
	option interface 'br-lan'
	option bind_network 'lan'
	option lookup_host 'vaiocn.ddnsfree.com'
	option domain 'vaiocn.ddnsfree.com'
	option force_dnstcp '1'

config service 'DynuHOME6'
	option service_name 'dynu.com'
	option use_ipv6 '1'
	option ip_source 'web'
	option ip_url 'http://192.168.1.119/ip6.html'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option username 'sqmshcn'
	option password 'dynuddns'
	option enabled '1'
	option lookup_host 'homecn.ddnsfree.com'
	option domain 'homecn.ddnsfree.com'
	option interface 'br-lan'
	option bind_network 'lan'
	option force_dnstcp '1'

config service 'DynuNAS6'
	option service_name 'dynu.com'
	option use_ipv6 '1'
	option enabled '1'
	option username 'sqmshcn'
	option password 'dynuddns'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option ip_source 'web'
	option ip_url 'http://192.168.1.8:8080/ip6.html'
	option interface 'br-lan'
	option bind_network 'lan'
	option lookup_host 'nascn.ddnsfree.com'
	option domain 'nascn.ddnsfree.com'
	option force_dnstcp '1'

config service 'DynuSSR6'
	option service_name 'dynu.com'
	option use_ipv6 '1'
	option enabled '1'
	option username 'sqmshcn'
	option password 'dynuddns'
	option use_syslog '2'
	option check_unit 'minutes'
	option force_unit 'minutes'
	option retry_unit 'seconds'
	option ip_source 'web'
	option ip_url 'http://192.168.1.110/ip6.html'
	option interface 'br-lan'
	option bind_network 'lan'
	option lookup_host 'ssrcn.ddnsfree.com'
	option domain 'ssrcn.ddnsfree.com'
	option force_dnstcp '1'
EOF
}
EOF
}

[ -f /etc/init.d/ttyd ] && {
cat > /etc/config/ttyd <<EOF
config ttyd
	option command '/bin/login'
	option debug '7'
	option ipv6 '1'
EOF
}

sed -i 's/root.*$/root:$1$TADtMues$II9qrw8S7H3hYtJASm0tw.:19059:0:99999:7:::/g' /etc/shadow
exit 0
